PAGADURIAS = {
    "COLPENSIONES": {"margen": 3000, "sector": "NACIONAL"},
    "FOPEP": {"margen": 5000, "sector": "NACIONAL"},
    "FIDUPREVISORA": {"margen": 5100, "sector": "NACIONAL"},
    "POSITIVA": {"margen": 5000, "sector": "NACIONAL"},
    "CASUR": {"margen": 20000, "sector": "NACIONAL"},
    "CREMIL": {"margen": 10000, "sector": "NACIONAL"},
    "COLFONDOS": {"margen": 5000, "sector": "PRIVADO"},
    "MAPFRE": {"margen": 5100, "sector": "PRIVADO"},
    "PORVENIR": {"margen": 5000, "sector": "PRIVADO"},
    "SEGUROS ALFA": {"margen": 5000, "sector": "PRIVADO"},
    "SKANDIA": {"margen": 5000, "sector": "PRIVADO"},
    "SURA": {"margen": 5000, "sector": "PRIVADO"},
    "ARL SURA": {"margen": 5000, "sector": "PRIVADO"},
    "PROTECCION": {"margen": 3000, "sector": "PRIVADO"},
    "ASULADO": {"margen": 3000, "sector": "PRIVADO"},
    "SECRETARIA DE EDUCACION DE CORDOBA": {"margen": 20000, "sector": "SEC EDU"},
    "SECRETARIA DE EDUCACION DE SUCRE": {"margen": 20000, "sector": "SEC EDU"},
    "SECRETARIA DE EDUCACION DE BOLIVAR": {"margen": 20000, "sector": "SEC EDU"},
    "SECRETARIA DE EDUCACION DEL ATLANTICO": {"margen": 20000, "sector": "SEC EDU"},
    "SECRETARIA DE EDUCACION DEL MAGDALENA": {"margen": 20000, "sector": "SEC EDU"},
    "SECRETARIA DE EDUCACION DEL CESAR": {"margen": 20000, "sector": "SEC EDU"},
    "SECRETARIA DE EDUCACION DE LA GUAJIRA": {"margen": 20000, "sector": "SEC EDU"},
    "SECRETARIA DE EDUCACION DE VALLEDUPAR": {"margen": 20000, "sector": "SEC EDU"}
}
